services:
  deeperseeker:
    build: .
    container_name: deeperseeker
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - HOST=0.0.0.0
      - DEEPSEEKER_DATA_DIR=/app/data
    env_file:
      - path: .env
        required: false
    volumes:
      - ./:/app
    shm_size: "1gb"
    restart: unless-stopped
